# https://travis-ci.org/bdarnell/plop
language: python
python:
  - 2.7
  - 3.6

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry pip install -r requirements-py27.txt; else travis_retry pip install -r requirements.txt; fi

script:
  - python -m plop.test.runtests

sudo: false
